[package]
org = "ballerina"
name = "grpc"
version = "0.8.0-beta.2"

[[platform.java11.dependency]]
path = "../grpc-native/build/libs/grpc-native-0.8.0-beta.2-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "grpc"
version = "0.8.0-beta.2-SNAPSHOT"

[[platform.java11.dependency]]
path = "../grpc-test-utils/build/libs/grpc-test-utils-0.8.0-beta.2-SNAPSHOT.jar"
groupId = "org.ballerinalang"
scope = "testOnly"
artifactId = "grpc"
version = "0.8.0-beta.2-SNAPSHOT"

[[platform.java11.dependency]]
path = "./lib/ballerina-cli-2.0.0-beta.2-20210704-232600-b9b185e9.jar"
groupId = "org.ballerinalang"
scope = "testOnly"
artifactId = "ballerina-cli"
version = "2.0.0-beta.2-20210704-232600-b9b185e9"

[[platform.java11.dependency]]
path = "./lib/antlr4-runtime-4.5.1.wso2v1.jar"
groupId = "org.wso2.orbit.org.antlr"
scope = "testOnly"
artifactId = "antlr4-runtime"
version = "4.5.1.wso2v1"

[[platform.java11.dependency]]
path = "./lib/http-native-1.1.0-beta.2-20210705-025900-45651fc.jar"
groupId = "org.ballerinalang"
artifactId = "http-native"
version = "1.1.0-beta.2-20210705-025900-45651fc"

[[platform.java11.dependency]]
path = "./lib/netty-common-4.1.65.Final.jar"
groupId = "io.netty"
artifactId = "netty-common"
version = "4.1.65.Final"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-4.1.65.Final.jar"
groupId = "io.netty"
artifactId = "netty-buffer"
version = "4.1.65.Final"

[[platform.java11.dependency]]
path = "./lib/netty-transport-4.1.65.Final.jar"
groupId = "io.netty"
artifactId = "netty-transport"
version = "4.1.65.Final"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-4.1.65.Final.jar"
groupId = "io.netty"
artifactId = "netty-resolver"
version = "4.1.65.Final"

[[platform.java11.dependency]]
path = "./lib/netty-handler-4.1.65.Final.jar"
groupId = "io.netty"
artifactId = "netty-handler"
version = "4.1.65.Final"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http-4.1.65.Final.jar"
groupId = "io.netty"
artifactId = "netty-codec-http"
version = "4.1.65.Final"

[[platform.java11.dependency]]
path = "./lib/netty-codec-4.1.65.Final.jar"
groupId = "io.netty"
artifactId = "netty-codec"
version = "4.1.65.Final"

[[platform.java11.dependency]]
path = "./lib/netty-handler-proxy-4.1.65.Final.jar"
groupId = "io.netty"
artifactId = "netty-handler-proxy"
version = "4.1.65.Final"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http2-4.1.65.Final.jar"
groupId = "io.netty"
artifactId = "netty-codec-http2"
version = "4.1.65.Final"

[[platform.java11.dependency]]
path = "./lib/commons-pool-1.5.6.wso2v1.jar"
groupId = "commons-pool.wso2"
artifactId = "commons-pool"
version = "1.5.6.wso2v1"

[[platform.java11.dependency]]
path = "./lib/bcprov-jdk15on-1.61.jar"
groupId = "org.bouncycastle"
artifactId = "bcprov-jdk15on"
version = "1.61"

[[platform.java11.dependency]]
path = "./lib/bcpkix-jdk15on-1.61.jar"
groupId = "org.bouncycastle"
artifactId = "bcpkix-jdk15on"
version = "1.61"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.39.Final.jar"
groupId = "io.netty"
artifactId = "netty-tcnative-boringssl-static"
version = "2.0.39.Final"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-3.9.1.jar"
groupId = "com.google.protobuf"
artifactId = "protobuf-java"
version = "3.9.1"

[[platform.java11.dependency]]
path = "./lib/proto-google-common-protos-1.17.0.jar"
groupId = "com.google.api.grpc"
artifactId = "proto-google-common-protos"
version = "1.17.0"

[[platform.java11.dependency]]
path = "./lib/formatter-core-2.0.0-beta.2-20210704-232600-b9b185e9.jar"
groupId = "org.ballerinalang"
artifactId = "formatter-core"
version = "2.0.0-beta.2-20210704-232600-b9b185e9"

[[platform.java11.dependency]]
path = "./lib/ballerina-parser-2.0.0-beta.2-20210704-232600-b9b185e9.jar"
groupId = "org.ballerinalang"
artifactId = "ballerina-parser"
version = "2.0.0-beta.2-20210704-232600-b9b185e9"
