[package]
org = "ballerina"
name = "grpc"
version = "1.2.0"
distribution = "2201.0.0"
authors = ["Ballerina"]
keywords = ["network", "grpc", "protobuf", "server-streaming", "client-streaming", "bidirectional-streaming"]
repository = "https://github.com/ballerina-platform/module-ballerina-grpc"
license = ["Apache-2.0"]
export = ["grpc", "grpc.types.duration", "grpc.types.struct", "grpc.types.timestamp", "grpc.types.wrappers", "grpc.types.any"]

[[platform.java11.dependency]]
path = "../native/build/libs/grpc-native-1.2.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/grpc-test-utils-1.2.0-SNAPSHOT.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/ballerina-cli-2201.0.0-20211221-194900-b414ea8e.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/antlr4-runtime-4.5.1.wso2v1.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/http-native-2.2.0-20211222-011200-f89d96e.jar"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-3.9.1.jar"

[[platform.java11.dependency]]
path = "./lib/proto-google-common-protos-1.17.0.jar"

[[platform.java11.dependency]]
path = "./lib/formatter-core-2201.0.0-20211221-194900-b414ea8e.jar"

[[platform.java11.dependency]]
path = "./lib/ballerina-parser-2201.0.0-20211221-194900-b414ea8e.jar"
